//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.18.0
//     from Assets/Inputs/PlayerInputs.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Inputs/PlayerInputs.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @PlayerInputs: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @PlayerInputs()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""PlayerInputs"",
    ""maps"": [
        {
            ""name"": ""PlayerInputActionMap"",
            ""id"": ""cd8f9e64-1033-436d-acb1-46c227c2c809"",
            ""actions"": [
                {
                    ""name"": ""FaceEast"",
                    ""type"": ""Button"",
                    ""id"": ""fa15228b-cc7a-4d14-ad8f-3dd189523cc6"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceNorth"",
                    ""type"": ""Button"",
                    ""id"": ""ebe1d16b-f535-4bfb-97d7-979c77752685"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceWest"",
                    ""type"": ""Button"",
                    ""id"": ""1ab8fa5d-a519-46e4-9698-ae784e2abe29"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""FaceSouth"",
                    ""type"": ""Button"",
                    ""id"": ""b422f4ab-1c91-41d6-8efc-6d7d47746b2e"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftModifier"",
                    ""type"": ""Button"",
                    ""id"": ""b24b8f9d-57da-47d6-8f8e-9513604d41d8"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightModifier"",
                    ""type"": ""Button"",
                    ""id"": ""fb97c8de-e37e-42e7-9a3e-fb367cbbc268"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftToggle"",
                    ""type"": ""Button"",
                    ""id"": ""154a0736-a51a-4912-ad61-d82ad5395244"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightToggle"",
                    ""type"": ""Button"",
                    ""id"": ""f1a37b57-d3b8-4e5d-8623-32b2db7c6316"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""LeftAction"",
                    ""type"": ""Button"",
                    ""id"": ""0d21e6b6-834f-46fb-bd1b-2ba3c3807fcf"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""RightAction"",
                    ""type"": ""Button"",
                    ""id"": ""4f929810-708c-409e-aff3-9356a9349c5b"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Move"",
                    ""type"": ""Value"",
                    ""id"": ""cf31f487-46c6-429a-a490-18e32bb0781f"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": ""StickDeadzone"",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                },
                {
                    ""name"": ""Look"",
                    ""type"": ""Value"",
                    ""id"": ""e3cfbc26-0e20-4264-ad92-19be551adf6d"",
                    ""expectedControlType"": ""Vector2"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": true
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""b28b2913-709e-4625-ba4e-39ed4b9e1b33"",
                    ""path"": ""<Gamepad>/buttonSouth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceSouth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""1afa1992-d7f4-4147-8de0-c8f0d3e9a857"",
                    ""path"": ""<Gamepad>/buttonEast"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceEast"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""825169a2-d9e7-4f4e-acc9-9201f305d085"",
                    ""path"": ""<Gamepad>/buttonNorth"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceNorth"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""3599dc5e-fc55-48cb-8f62-f16345e514da"",
                    ""path"": ""<Gamepad>/buttonWest"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""FaceWest"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""943c3773-397a-4b50-8fc5-cecd793d8bd9"",
                    ""path"": ""<Gamepad>/leftShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""834315df-4968-4d8d-991a-064a0412be2e"",
                    ""path"": ""<Gamepad>/rightShoulder"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightModifier"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""f3f038cd-bdff-4e20-88b0-ee229ac00a69"",
                    ""path"": ""<Gamepad>/leftStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""aa31e9ed-bf4c-4c5a-960d-e7db11c4be57"",
                    ""path"": ""<Gamepad>/rightStickPress"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightToggle"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""81d71c81-b900-46bb-a024-9402a44d108c"",
                    ""path"": ""<Gamepad>/leftTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""LeftAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""95256145-30d3-4a66-b2d6-9d99b002a63e"",
                    ""path"": ""<Gamepad>/rightTrigger"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""RightAction"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""d9e2e6f3-d7c1-4929-9f32-73d6257e4a84"",
                    ""path"": ""<Gamepad>/leftStick"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Move"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""554387cb-791f-41b5-813a-2afe3e99b11c"",
                    ""path"": ""<Gamepad>/rightStick"",
                    ""interactions"": """",
                    ""processors"": ""ScaleVector2,StickDeadzone"",
                    ""groups"": """",
                    ""action"": ""Look"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // PlayerInputActionMap
        m_PlayerInputActionMap = asset.FindActionMap("PlayerInputActionMap", throwIfNotFound: true);
        m_PlayerInputActionMap_FaceEast = m_PlayerInputActionMap.FindAction("FaceEast", throwIfNotFound: true);
        m_PlayerInputActionMap_FaceNorth = m_PlayerInputActionMap.FindAction("FaceNorth", throwIfNotFound: true);
        m_PlayerInputActionMap_FaceWest = m_PlayerInputActionMap.FindAction("FaceWest", throwIfNotFound: true);
        m_PlayerInputActionMap_FaceSouth = m_PlayerInputActionMap.FindAction("FaceSouth", throwIfNotFound: true);
        m_PlayerInputActionMap_LeftModifier = m_PlayerInputActionMap.FindAction("LeftModifier", throwIfNotFound: true);
        m_PlayerInputActionMap_RightModifier = m_PlayerInputActionMap.FindAction("RightModifier", throwIfNotFound: true);
        m_PlayerInputActionMap_LeftToggle = m_PlayerInputActionMap.FindAction("LeftToggle", throwIfNotFound: true);
        m_PlayerInputActionMap_RightToggle = m_PlayerInputActionMap.FindAction("RightToggle", throwIfNotFound: true);
        m_PlayerInputActionMap_LeftAction = m_PlayerInputActionMap.FindAction("LeftAction", throwIfNotFound: true);
        m_PlayerInputActionMap_RightAction = m_PlayerInputActionMap.FindAction("RightAction", throwIfNotFound: true);
        m_PlayerInputActionMap_Move = m_PlayerInputActionMap.FindAction("Move", throwIfNotFound: true);
        m_PlayerInputActionMap_Look = m_PlayerInputActionMap.FindAction("Look", throwIfNotFound: true);
    }

    ~@PlayerInputs()
    {
        UnityEngine.Debug.Assert(!m_PlayerInputActionMap.enabled, "This will cause a leak and performance issues, PlayerInputs.PlayerInputActionMap.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // PlayerInputActionMap
    private readonly InputActionMap m_PlayerInputActionMap;
    private List<IPlayerInputActionMapActions> m_PlayerInputActionMapActionsCallbackInterfaces = new List<IPlayerInputActionMapActions>();
    private readonly InputAction m_PlayerInputActionMap_FaceEast;
    private readonly InputAction m_PlayerInputActionMap_FaceNorth;
    private readonly InputAction m_PlayerInputActionMap_FaceWest;
    private readonly InputAction m_PlayerInputActionMap_FaceSouth;
    private readonly InputAction m_PlayerInputActionMap_LeftModifier;
    private readonly InputAction m_PlayerInputActionMap_RightModifier;
    private readonly InputAction m_PlayerInputActionMap_LeftToggle;
    private readonly InputAction m_PlayerInputActionMap_RightToggle;
    private readonly InputAction m_PlayerInputActionMap_LeftAction;
    private readonly InputAction m_PlayerInputActionMap_RightAction;
    private readonly InputAction m_PlayerInputActionMap_Move;
    private readonly InputAction m_PlayerInputActionMap_Look;
    /// <summary>
    /// Provides access to input actions defined in input action map "PlayerInputActionMap".
    /// </summary>
    public struct PlayerInputActionMapActions
    {
        private @PlayerInputs m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public PlayerInputActionMapActions(@PlayerInputs wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/FaceEast".
        /// </summary>
        public InputAction @FaceEast => m_Wrapper.m_PlayerInputActionMap_FaceEast;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/FaceNorth".
        /// </summary>
        public InputAction @FaceNorth => m_Wrapper.m_PlayerInputActionMap_FaceNorth;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/FaceWest".
        /// </summary>
        public InputAction @FaceWest => m_Wrapper.m_PlayerInputActionMap_FaceWest;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/FaceSouth".
        /// </summary>
        public InputAction @FaceSouth => m_Wrapper.m_PlayerInputActionMap_FaceSouth;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/LeftModifier".
        /// </summary>
        public InputAction @LeftModifier => m_Wrapper.m_PlayerInputActionMap_LeftModifier;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/RightModifier".
        /// </summary>
        public InputAction @RightModifier => m_Wrapper.m_PlayerInputActionMap_RightModifier;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/LeftToggle".
        /// </summary>
        public InputAction @LeftToggle => m_Wrapper.m_PlayerInputActionMap_LeftToggle;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/RightToggle".
        /// </summary>
        public InputAction @RightToggle => m_Wrapper.m_PlayerInputActionMap_RightToggle;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/LeftAction".
        /// </summary>
        public InputAction @LeftAction => m_Wrapper.m_PlayerInputActionMap_LeftAction;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/RightAction".
        /// </summary>
        public InputAction @RightAction => m_Wrapper.m_PlayerInputActionMap_RightAction;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/Move".
        /// </summary>
        public InputAction @Move => m_Wrapper.m_PlayerInputActionMap_Move;
        /// <summary>
        /// Provides access to the underlying input action "PlayerInputActionMap/Look".
        /// </summary>
        public InputAction @Look => m_Wrapper.m_PlayerInputActionMap_Look;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_PlayerInputActionMap; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="PlayerInputActionMapActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(PlayerInputActionMapActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="PlayerInputActionMapActions" />
        public void AddCallbacks(IPlayerInputActionMapActions instance)
        {
            if (instance == null || m_Wrapper.m_PlayerInputActionMapActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_PlayerInputActionMapActionsCallbackInterfaces.Add(instance);
            @FaceEast.started += instance.OnFaceEast;
            @FaceEast.performed += instance.OnFaceEast;
            @FaceEast.canceled += instance.OnFaceEast;
            @FaceNorth.started += instance.OnFaceNorth;
            @FaceNorth.performed += instance.OnFaceNorth;
            @FaceNorth.canceled += instance.OnFaceNorth;
            @FaceWest.started += instance.OnFaceWest;
            @FaceWest.performed += instance.OnFaceWest;
            @FaceWest.canceled += instance.OnFaceWest;
            @FaceSouth.started += instance.OnFaceSouth;
            @FaceSouth.performed += instance.OnFaceSouth;
            @FaceSouth.canceled += instance.OnFaceSouth;
            @LeftModifier.started += instance.OnLeftModifier;
            @LeftModifier.performed += instance.OnLeftModifier;
            @LeftModifier.canceled += instance.OnLeftModifier;
            @RightModifier.started += instance.OnRightModifier;
            @RightModifier.performed += instance.OnRightModifier;
            @RightModifier.canceled += instance.OnRightModifier;
            @LeftToggle.started += instance.OnLeftToggle;
            @LeftToggle.performed += instance.OnLeftToggle;
            @LeftToggle.canceled += instance.OnLeftToggle;
            @RightToggle.started += instance.OnRightToggle;
            @RightToggle.performed += instance.OnRightToggle;
            @RightToggle.canceled += instance.OnRightToggle;
            @LeftAction.started += instance.OnLeftAction;
            @LeftAction.performed += instance.OnLeftAction;
            @LeftAction.canceled += instance.OnLeftAction;
            @RightAction.started += instance.OnRightAction;
            @RightAction.performed += instance.OnRightAction;
            @RightAction.canceled += instance.OnRightAction;
            @Move.started += instance.OnMove;
            @Move.performed += instance.OnMove;
            @Move.canceled += instance.OnMove;
            @Look.started += instance.OnLook;
            @Look.performed += instance.OnLook;
            @Look.canceled += instance.OnLook;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="PlayerInputActionMapActions" />
        private void UnregisterCallbacks(IPlayerInputActionMapActions instance)
        {
            @FaceEast.started -= instance.OnFaceEast;
            @FaceEast.performed -= instance.OnFaceEast;
            @FaceEast.canceled -= instance.OnFaceEast;
            @FaceNorth.started -= instance.OnFaceNorth;
            @FaceNorth.performed -= instance.OnFaceNorth;
            @FaceNorth.canceled -= instance.OnFaceNorth;
            @FaceWest.started -= instance.OnFaceWest;
            @FaceWest.performed -= instance.OnFaceWest;
            @FaceWest.canceled -= instance.OnFaceWest;
            @FaceSouth.started -= instance.OnFaceSouth;
            @FaceSouth.performed -= instance.OnFaceSouth;
            @FaceSouth.canceled -= instance.OnFaceSouth;
            @LeftModifier.started -= instance.OnLeftModifier;
            @LeftModifier.performed -= instance.OnLeftModifier;
            @LeftModifier.canceled -= instance.OnLeftModifier;
            @RightModifier.started -= instance.OnRightModifier;
            @RightModifier.performed -= instance.OnRightModifier;
            @RightModifier.canceled -= instance.OnRightModifier;
            @LeftToggle.started -= instance.OnLeftToggle;
            @LeftToggle.performed -= instance.OnLeftToggle;
            @LeftToggle.canceled -= instance.OnLeftToggle;
            @RightToggle.started -= instance.OnRightToggle;
            @RightToggle.performed -= instance.OnRightToggle;
            @RightToggle.canceled -= instance.OnRightToggle;
            @LeftAction.started -= instance.OnLeftAction;
            @LeftAction.performed -= instance.OnLeftAction;
            @LeftAction.canceled -= instance.OnLeftAction;
            @RightAction.started -= instance.OnRightAction;
            @RightAction.performed -= instance.OnRightAction;
            @RightAction.canceled -= instance.OnRightAction;
            @Move.started -= instance.OnMove;
            @Move.performed -= instance.OnMove;
            @Move.canceled -= instance.OnMove;
            @Look.started -= instance.OnLook;
            @Look.performed -= instance.OnLook;
            @Look.canceled -= instance.OnLook;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="PlayerInputActionMapActions.UnregisterCallbacks(IPlayerInputActionMapActions)" />.
        /// </summary>
        /// <seealso cref="PlayerInputActionMapActions.UnregisterCallbacks(IPlayerInputActionMapActions)" />
        public void RemoveCallbacks(IPlayerInputActionMapActions instance)
        {
            if (m_Wrapper.m_PlayerInputActionMapActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="PlayerInputActionMapActions.AddCallbacks(IPlayerInputActionMapActions)" />
        /// <seealso cref="PlayerInputActionMapActions.RemoveCallbacks(IPlayerInputActionMapActions)" />
        /// <seealso cref="PlayerInputActionMapActions.UnregisterCallbacks(IPlayerInputActionMapActions)" />
        public void SetCallbacks(IPlayerInputActionMapActions instance)
        {
            foreach (var item in m_Wrapper.m_PlayerInputActionMapActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_PlayerInputActionMapActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="PlayerInputActionMapActions" /> instance referencing this action map.
    /// </summary>
    public PlayerInputActionMapActions @PlayerInputActionMap => new PlayerInputActionMapActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "PlayerInputActionMap" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="PlayerInputActionMapActions.AddCallbacks(IPlayerInputActionMapActions)" />
    /// <seealso cref="PlayerInputActionMapActions.RemoveCallbacks(IPlayerInputActionMapActions)" />
    public interface IPlayerInputActionMapActions
    {
        /// <summary>
        /// Method invoked when associated input action "FaceEast" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFaceEast(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FaceNorth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFaceNorth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FaceWest" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFaceWest(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "FaceSouth" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnFaceSouth(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftModifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftModifier(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightModifier" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightModifier(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightToggle" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightToggle(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "LeftAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLeftAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "RightAction" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnRightAction(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Move" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnMove(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Look" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnLook(InputAction.CallbackContext context);
    }
}
